config/routes.rb
PerfReport::Application.routes.draw do
  resources :server_applications


  resources :applications


  require 'sidekiq/web'

  resources :graph_types
  resource :help, :controller => 'help' do
    get :about
    get :download_manual
  end


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :account, :controller => :account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :users, :only => [:show]

  authenticated :user do
    root :to => 'reports#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  resources :reports do
    member do
      post :generate
    end
  end
  resources :graphs, :only => [:index, :show, :destroy]
  resources :servers, :only => [:index, :show, :destroy]
  resources :report_files do
    resources :report_file_emails, :only => [:new, :create, :send_email] do
      collection do
        get :send_email
      end
    end
  end
  resources :server_groups
  resources :graph_commands



  namespace :api, :defaults => {:format => :json}  do
    resources :reports do
      member do
        get :generate
        get :generate_status
        get :user_report_files
      end
    end
    resources :report_files

    resources :graph_sources do
      resources :graph_commands
    end
  end

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :graph_sources
  end

  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/controllers/graph_types_controller.rb
class GraphTypesController < ApplicationController
  load_and_authorize_resource

  # GET /graph_types
  # GET /graph_types.json
  def index
    @graph_types = GraphType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @graph_types }
    end
  end

  # GET /graph_types/1
  # GET /graph_types/1.json
  def show
    @graph_type = GraphType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @graph_type }
    end
  end

  # GET /graph_types/new
  # GET /graph_types/new.json
  def new
    @graph_type = GraphType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @graph_type }
    end
  end

  # GET /graph_types/1/edit
  def edit
    @graph_type = GraphType.find(params[:id])
  end

  # POST /graph_types
  # POST /graph_types.json
  def create
    @graph_type = GraphType.new(params[:graph_type])
    @graph_type.user = current_user

    respond_to do |format|
      if @graph_type.save
        format.html { redirect_to @graph_type, notice: 'Graph type was successfully created.' }
        format.json { render json: @graph_type, status: :created, location: @graph_type }
      else
        format.html { render action: "new" }
        format.json { render json: @graph_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /graph_types/1
  # PUT /graph_types/1.json
  def update
    @graph_type = GraphType.find(params[:id])

    respond_to do |format|
      if @graph_type.update_attributes(params[:graph_type])
        format.html { redirect_to @graph_type, notice: 'Graph type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @graph_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graph_types/1
  # DELETE /graph_types/1.json
  def destroy
    @graph_type = GraphType.find(params[:id])
    @graph_type.destroy

    respond_to do |format|
      format.html { redirect_to graph_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/graph_types_helper.rb
module GraphTypesHelper
end

app/views/graph_types/_form.html.erb
<%= form_for(@graph_type) do |f| %>
  <% if @graph_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graph_type.errors.count, "error") %> prohibited this graph_type from being saved:</h2>

      <ul>
      <% @graph_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :display_order %><br />
    <%= f.number_field :display_order %> (<%= t('graph_types.tips.display_order') %>)
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graph_types/_graph_type.html.erb
<tr id="graph_type_<%= graph_type.id %>">
  <td><%= link_to graph_type.name, graph_type %></td>
  <td><%= graph_type.display_order %></td>
  <td><%= graph_type.user.nil? ? t('general.system') : graph_type.user.name %></td>
  <td>
    <% if can? :edit, GraphType %>
        <%= link_to t('general.edit'), edit_graph_type_path(graph_type) %>
    <% end %>
    <% if can? :destroy, GraphType %>
        <%= link_to t('general.delete'), graph_type, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </td>
</tr>

app/views/graph_types/_graph_types.html.erb
<div class="table">
  <table class='data_table' id="graph_type_table">
    <thead>
    <tr>
      <th><%= t('general.name') %></th>
      <th><%= t('graph_types.display_order') %></th>
      <th><%= t('general.created_by') %></th>
      <th><%= t('general.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <% graph_types.each do |graph_type| %>
        <%= render graph_type %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/graph_types/edit.html.erb
<h1><%= t('general.editing') % t('graph_types.graph_type') %></h1>

<%= render 'form' %>

<%= render 'layouts/view_footer' %>

app/views/graph_types/index.html.erb
<h1><%= t('general.listing') % t('graph_types.graph_types') %>
  <% if can? :create, GraphType %>
    <span class='actions'>
      <%= link_to t('general.new'), new_graph_type_path, :id => 'new_graph_type_link' %>
    </span>
  <% end %>
</h1>

<%= render 'graph_types/graph_types', :graph_types => @graph_types %>

app/views/graph_types/new.html.erb
<h1><%= t('general.new_model') % t('graph_types.graph_type') %></h1>

<%= render 'form' %>

<%= render 'layouts/view_footer' %>

app/views/graph_types/show.html.erb
<h1><%= @graph_type.name %> </h1>

<p>
  <b><%= t('general.owner') %>:</b>
  <%= @graph_type.user.name %> <br />

  <b><%= t('graph_types.display_order') %>:</b>
  <%= @graph_type.display_order %>
</p>
<br />
<br />
<%= edit_html(edit_graph_type_path(@graph_type), GraphType) %>
<%= link_to t('general.back'), reports_path %>