config/routes.rb
PerfReport::Application.routes.draw do
  resources :server_applications


  resources :applications


  require 'sidekiq/web'

  resources :graph_types
  resource :help, :controller => 'help' do
    get :about
    get :download_manual
  end


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :account, :controller => :account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :users, :only => [:show]

  authenticated :user do
    root :to => 'reports#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  resources :reports do
    member do
      post :generate
    end
  end
  resources :graphs, :only => [:index, :show, :destroy]
  resources :servers, :only => [:index, :show, :destroy]
  resources :report_files do
    resources :report_file_emails, :only => [:new, :create, :send_email] do
      collection do
        get :send_email
      end
    end
  end
  resources :server_groups
  resources :graph_commands



  namespace :api, :defaults => {:format => :json}  do
    resources :reports do
      member do
        get :generate
        get :generate_status
        get :user_report_files
      end
    end
    resources :report_files

    resources :graph_sources do
      resources :graph_commands
    end
  end

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :graph_sources
  end

  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  audited

  attr_accessible :active, :app_type, :ignore_active, :major_application, :name

  validates :app_type,  :presence => true
  validates :name,      :presence => true,
            :uniqueness => true

  APP_INFO_END_POINT = 'applications'

  belongs_to :user

  has_many :report_applications
  has_many :application_family_applications

  has_many :server_applications, :dependent => :destroy

  has_many :application_families, :through => :application_family_applications
  has_many :servers, :through => :server_applications

  def self.create_and_update
    created_updated = Array.new

    attr = {
        :name              => 'name',
        :app_type          => 'app_type',
        :major_application => 'major_application',
    }

    resources = AppInfo.retrieve_resources APP_CONFIG, APP_INFO_END_POINT, Application, attr, 'name'

    if resources
      resources.each do |resource_title, resource|
        current_resource = find_by_name(resource_title)

        if current_resource
          unless (current_resource.app_type == resource.app_type) &&
              (current_resource.major_application == resource.major_application)
            # Update the existing resource
            current_resource.app_type           = resource.app_type           unless current_resource.app_type == resource.app_type
            current_resource.major_application  = resource.major_application  unless current_resource.major_application == resource.major_application

            created_updated << current_resource
            current_resource.save
          end
        else
          created_updated << resource
          resource.save
        end
      end
    end

    created_updated
  end

  def self.remove_stale
    api_resources = (AppInfo.retrieve_resources APP_CONFIG, APP_INFO_END_POINT, Application, {:name => 'name'}, 'name').map { |n,r| r.name.downcase }

    resources = all.map { |r| r.name.downcase }

    to_delete = (resources - api_resources)

    to_delete.each do |r|
      find_by_name(r).delete
    end

    to_delete
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_timezone

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      flash[:alert] = t('user.not_authorized')
      session[:user_return_to] = nil

      if params[:redirect_to]
        redirect_path = params[:redirect_to]
      else
        redirect_path = (current_user.roles.count == 2 && current_user.has_role?(:admin)) ? admin_path : root_path
      end

      respond_to do |format|
        format.html { redirect_to redirect_path }
        format.json { render json: { :message => flash[:error], :url => request.url } }
      end

    else
      flash[:alert] = t('user.login_first')
      session[:user_return_to] = request.url

      respond_to do |format|
        format.html { redirect_to '/users/sign_in' }
        format.json { render json: { :message => flash[:error], :url => request.url } }
      end
    end
  end

  def set_timezone
    Time.zone = current_user.time_zone if current_user
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    if resource.email == SYSTEM_USER_ACCOUNT_EMAIL
      destroy_user_session_path
      raise CanCan::AccessDenied
    elsif resource.has_role?(:admin) && resource.roles.count == 2
      admin_path
    else
      root_path
    end
  end

  def owner_check_read
    report = Report.find(params[:id])
    unless report.can_read?(current_user)
      params[:redirect_to] = reports_path
      raise CanCan::AccessDenied
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def application_params
      params.require(:application).permit(:active, :app_type, :ignore_active, :major_application, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_users_home
    if !current_user.nil? && (current_user.has_role?(:admin) && current_user.roles.count == 1)
      admin_path
    else
      root_path
    end
  end

  def bool_to_word(boolean)
    if boolean
      'yes'
    else
      'no'
    end
  end

  def edit_html(path, class_type)
    html = ''
    if can?(:edit, class_type)
      html = "#{link_to t('general.edit'), path} |".html_safe
    end

    html
  end

  def user_public_link(user)
   link_to user.name, user_path(user),
            :title    => '',
            :class    => 'popover_link',
            :data     => {
                :content  => render('users/public_popover',
                                     :user    => user
                ).html_safe,
            }
  end

  def avatar_url(user, size = 80)
    if user.user_profile
      if user.user_profile.avatar_url.present?
        user.user_profile.avatar_url
      else
        user.user_profile.gravatar_url(:size => size)
      end
    end
  end

  def show_avatar
    APP_CONFIG["user_profiles"].present? && APP_CONFIG["user_profiles"]["show_avatars"]
  end

  def branding_title
    title = ''

    title = "#{APP_CONFIG['branding']['title']} - " if APP_CONFIG['branding'] && APP_CONFIG['branding']['title']

    "#{title}#{t('perfreport.perfreports')}"
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :app_type %><br />
    <%= f.text_field :app_type %>
  </div>
  <div class="field">
    <%= f.label :major_application %><br />
    <%= f.text_field :major_application %>
  </div>
  <div class="field">
    <%= f.label :ignore_active %><br />
    <%= f.check_box :ignore_active %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>App type</th>
    <th>Major application</th>
    <th>Ignore active</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applications.each do |application| %>
  <tr>
    <td><%= application.name %></td>
    <td><%= application.app_type %></td>
    <td><%= application.major_application %></td>
    <td><%= application.ignore_active %></td>
    <td><%= application.active %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @application.name %>
</p>

<p>
  <b>App type:</b>
  <%= @application.app_type %>
</p>

<p>
  <b>Major application:</b>
  <%= @application.major_application %>
</p>

<p>
  <b>Ignore active:</b>
  <%= @application.ignore_active %>
</p>

<p>
  <b>Active:</b>
  <%= @application.active %>
</p>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>