config/routes.rb
PerfReport::Application.routes.draw do
  resources :server_applications


  resources :applications


  require 'sidekiq/web'

  resources :graph_types
  resource :help, :controller => 'help' do
    get :about
    get :download_manual
  end


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :account, :controller => :account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :users, :only => [:show]

  authenticated :user do
    root :to => 'reports#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  resources :reports do
    member do
      post :generate
    end
  end
  resources :graphs, :only => [:index, :show, :destroy]
  resources :servers, :only => [:index, :show, :destroy]
  resources :report_files do
    resources :report_file_emails, :only => [:new, :create, :send_email] do
      collection do
        get :send_email
      end
    end
  end
  resources :server_groups
  resources :graph_commands



  namespace :api, :defaults => {:format => :json}  do
    resources :reports do
      member do
        get :generate
        get :generate_status
        get :user_report_files
      end
    end
    resources :report_files

    resources :graph_sources do
      resources :graph_commands
    end
  end

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :graph_sources
  end

  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  audited

  attr_accessible :active, :app_type, :ignore_active, :major_application, :name

  validates :app_type,  :presence => true
  validates :name,      :presence => true,
            :uniqueness => true

  APP_INFO_END_POINT = 'applications'

  belongs_to :user

  has_many :report_applications
  has_many :application_family_applications

  has_many :server_applications, :dependent => :destroy

  has_many :application_families, :through => :application_family_applications
  has_many :servers, :through => :server_applications

  def self.create_and_update
    created_updated = Array.new

    attr = {
        :name              => 'name',
        :app_type          => 'app_type',
        :major_application => 'major_application',
    }

    resources = AppInfo.retrieve_resources APP_CONFIG, APP_INFO_END_POINT, Application, attr, 'name'

    if resources
      resources.each do |resource_title, resource|
        current_resource = find_by_name(resource_title)

        if current_resource
          unless (current_resource.app_type == resource.app_type) &&
              (current_resource.major_application == resource.major_application)
            # Update the existing resource
            current_resource.app_type           = resource.app_type           unless current_resource.app_type == resource.app_type
            current_resource.major_application  = resource.major_application  unless current_resource.major_application == resource.major_application

            created_updated << current_resource
            current_resource.save
          end
        else
          created_updated << resource
          resource.save
        end
      end
    end

    created_updated
  end

  def self.remove_stale
    api_resources = (AppInfo.retrieve_resources APP_CONFIG, APP_INFO_END_POINT, Application, {:name => 'name'}, 'name').map { |n,r| r.name.downcase }

    resources = all.map { |r| r.name.downcase }

    to_delete = (resources - api_resources)

    to_delete.each do |r|
      find_by_name(r).delete
    end

    to_delete
  end
end

app/models/server_group.rb
class ServerGroup < ActiveRecord::Base
  audited

  attr_accessible :name, :user_id, :server_ids

  validates :name, presence: true,
                   uniqueness: true

  belongs_to :user
  has_many :server_group_profiles
  has_many :servers, :through => :server_group_profiles
end

app/controllers/server_groups_controller.rb
class ServerGroupsController < ApplicationController
  load_and_authorize_resource

  # GET /server_groups
  # GET /server_groups.json
  def index
    @server_groups = ServerGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @server_groups }
    end
  end

  # GET /server_groups/1
  # GET /server_groups/1.json
  def show
    @server_group = ServerGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server_group }
    end
  end

  # GET /server_groups/new
  # GET /server_groups/new.json
  def new
    @server_group = ServerGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server_group }
    end
  end

  # GET /server_groups/1/edit
  def edit
    @server_group = ServerGroup.find(params[:id])
  end

  # POST /server_groups
  # POST /server_groups.json
  def create
    @server_group = ServerGroup.new(params[:server_group])
    @server_group.user = current_user

    respond_to do |format|
      if @server_group.save
        format.html { redirect_to @server_group, notice: 'Server group was successfully created.' }
        format.json { render json: @server_group, status: :created, location: @server_group }
      else
        format.html { render action: "new" }
        format.json { render json: @server_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /server_groups/1
  # PUT /server_groups/1.json
  def update
    @server_group = ServerGroup.find(params[:id])

    respond_to do |format|
      if @server_group.update_attributes(params[:server_group])
        format.html { redirect_to @server_group, notice: 'Server group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_groups/1
  # DELETE /server_groups/1.json
  def destroy
    @server_group = ServerGroup.find(params[:id])
    @server_group.destroy

    respond_to do |format|
      format.html { redirect_to server_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/server_groups_helper.rb
module ServerGroupsHelper
end

app/views/server_groups/_form.html.erb
<%= form_for(@server_group) do |f| %>
  <% if @server_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server_group.errors.count, "error") %> prohibited this server_group from being saved:</h2>

      <ul>
      <% @server_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field server_select">
    <%= f.label :servers %>
    <%= f.collection_select :server_ids, Server.order(:name).all.collect, :id, :name, {}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/server_groups/_server_group.html.erb
<tr id="server_group_<%= server_group.id %>">
  <td><%= link_to server_group.name, server_group %></td>
  <td>
    <% if can? :edit, ServerGroup %>
        <%= link_to t('general.edit'), edit_server_group_path(server_group) %>
    <% end %>
    <% if can? :destroy, ServerGroup %>
        <%= link_to t('general.delete'), server_group, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </td>
</tr>

app/views/server_groups/_server_groups.html.erb
<div>
  <table class='data_table' id="server_groups_table">
    <thead>
    <tr>
      <th><%= t('general.name') %></th>
      <th><%= t('general.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <% server_groups.each do |server_group| %>
        <%= render server_group %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/server_groups/edit.html.erb
<h1><%= t('general.editing') % t('server_groups.server_groups') %></h1>

<%= render 'form' %>

<%= render 'layouts/view_footer' %>

app/views/server_groups/index.html.erb
<br />
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('server_groups.server_groups') %>
  </div>
  <div class="panel-body">
    <%= render 'server_groups/server_groups', :server_groups => @server_groups %>
  </div>
</div>
<% if can? :create, ServerGroup %>
    <span class='actions'>
      <%= link_to t('general.new'), new_server_group_path, :id => 'new_server_group_link' %>
    </span>
<% end %>

app/views/server_groups/new.html.erb
<h1><%= t('general.new') % t('server_groups.server_groups') %></h1>

<%= render 'form' %>

<%= render 'layouts/view_footer' %>

app/views/server_groups/show.html.erb
<h1><%= @server_group.name %></h1>

<p>
  <b><%= t('general.owner') %>:</b>
  <%= @server_group.user.name %>
</p>
<br />
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('servers.servers') %>
  </div>
  <div class="panel-body">
    <%= render 'servers/servers', :servers => @server_group.servers.order(:name) %>
  </div>
</div>
<br />
<br />
<br />
<%= edit_html(edit_server_group_path(@server_group), ServerGroup) %>
<%= link_to t('general.back'), reports_path %>