config/routes.rb
PerfReport::Application.routes.draw do
  resources :server_applications


  resources :applications


  require 'sidekiq/web'

  resources :graph_types
  resource :help, :controller => 'help' do
    get :about
    get :download_manual
  end


  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :account, :controller => :account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :users, :only => [:show]

  authenticated :user do
    root :to => 'reports#index', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  resources :reports do
    member do
      post :generate
    end
  end
  resources :graphs, :only => [:index, :show, :destroy]
  resources :servers, :only => [:index, :show, :destroy]
  resources :report_files do
    resources :report_file_emails, :only => [:new, :create, :send_email] do
      collection do
        get :send_email
      end
    end
  end
  resources :server_groups
  resources :graph_commands



  namespace :api, :defaults => {:format => :json}  do
    resources :reports do
      member do
        get :generate
        get :generate_status
        get :user_report_files
      end
    end
    resources :report_files

    resources :graph_sources do
      resources :graph_commands
    end
  end

  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
    resources :graph_sources
  end

  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  audited

  attr_accessible :active, :app_type, :ignore_active, :major_application, :name

  validates :app_type,  :presence => true
  validates :name,      :presence => true,
            :uniqueness => true

  APP_INFO_END_POINT = 'applications'

  belongs_to :user

  has_many :report_applications
  has_many :application_family_applications

  has_many :server_applications, :dependent => :destroy

  has_many :application_families, :through => :application_family_applications
  has_many :servers, :through => :server_applications

  def self.create_and_update
    created_updated = Array.new

    attr = {
        :name              => 'name',
        :app_type          => 'app_type',
        :major_application => 'major_application',
    }

    resources = AppInfo.retrieve_resources APP_CONFIG, APP_INFO_END_POINT, Application, attr, 'name'

    if resources
      resources.each do |resource_title, resource|
        current_resource = find_by_name(resource_title)

        if current_resource
          unless (current_resource.app_type == resource.app_type) &&
              (current_resource.major_application == resource.major_application)
            # Update the existing resource
            current_resource.app_type           = resource.app_type           unless current_resource.app_type == resource.app_type
            current_resource.major_application  = resource.major_application  unless current_resource.major_application == resource.major_application

            created_updated << current_resource
            current_resource.save
          end
        else
          created_updated << resource
          resource.save
        end
      end
    end

    created_updated
  end

  def self.remove_stale
    api_resources = (AppInfo.retrieve_resources APP_CONFIG, APP_INFO_END_POINT, Application, {:name => 'name'}, 'name').map { |n,r| r.name.downcase }

    resources = all.map { |r| r.name.downcase }

    to_delete = (resources - api_resources)

    to_delete.each do |r|
      find_by_name(r).delete
    end

    to_delete
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  audited

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, :registerable,
         :recoverable, :rememberable, :trackable,
         :confirmable, :lockable

  devise :omniauthable, :omniauth_providers => [:auth_man]

  include RoleModel

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :time_zone, :fname, :lname, :roles, :role_mask,
                  :user_profile, :user_profile_attributes, :encrypted_password, :password_salt

  validates :fname, :presence => true
  validates :lname, :presence => true

  validate :limited_servers

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :report_generator, :report_admin, :limited_servers, :normal_user

  has_one :user_profile

  has_many :reports
  has_many :server_regexes
  has_many :graph_commands
  has_many :shared_reports
  has_many :server_groups
  has_many :graph_types
  has_many :graph_sources
  has_many :report_files
  has_many :applications
  has_many :server_applications
  has_many :report_applications
  has_many :application_family
  has_many :application_family_application
  has_many :report_application_family

  accepts_nested_attributes_for :user_profile

  before_save :add_default_roles
  after_save :mailer
  after_destroy :destroy_mailer
  after_destroy :orphan_reports
  after_create :setup_profile

  DEFAULT_ROLES = [
      :normal_user
  ]

  ROLE_DESCRIPTIONS = {
      :admin  => 'Can create/edit/delete users.',
      :report_generator  => 'Can create and edit/delete their own reports.',
      :report_admin  => 'Can create and edit/delete any reports.',
      :limited_servers  => 'Can only create reports for a subset of servers.',
      :normal_user  => 'Can generate preexisting reports.'
  }

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def full_name
    self.fname && self.lname ? "#{self.fname} #{self.lname}" : nil
  end

  def full_name_comma
    self.fname && self.lname ? "#{self.lname}, #{self.fname}" : nil
  end

  def name
    self.fname && self.lname ? "#{self.fname} #{self.lname}" : self.email
  end

  def self.from_omniauth(auth)
    user_return = where(provider: auth.provider, uid: auth.uid).first

    unless user_return
      user = User.new(
          :email        => auth.info.email,
          :password     => Devise.friendly_token[0,20],
          :fname        => auth.info.fname,
          :lname        => auth.info.lname,
          :time_zone    => auth.info.time_zone,
      )

      user.uid      = auth.uid
      user.provider = auth.provider

      user.skip_confirmation!
      user.save

      user_return = user
    end

    user_return.sync_with_omniauth(auth)

    user_return
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.auth_man_data'] && session['devise.auth_man_data']['extra']['raw_info']
        user.email      = data['email'] if user.email.blank?
        user.fname      = data['fname'] if user.fname.blank?
        user.lname      = data['lname'] if user.lname.blank?
        user.time_zone  = data['time_zone'] if user.time_zone.blank?
      end
    end
  end

  def sync_with_omniauth(auth)
    unless auth.info.fname == self.fname && auth.info.lname == self.lname && auth.info.time_zone == self.time_zone
      self.fname      = auth.info.fname
      self.lname      = auth.info.lname
      self.time_zone  = auth.info.time_zone

      self.save
    end
  end

  private
  def valid_roles
    if self.roles_mask.nil? || self.roles_mask < 1
      errors.add(:base, 'At least one role must be selected')
    end
  end

  def add_default_roles
    DEFAULT_ROLES.each do |role|
      self.roles << role unless self.has_role?(role)
    end
  end

  def mailer
    if self.roles_mask_changed? && self.confirmed?
      AdminUsersMailer.delay.roles_changed_email(self)
    end
  end

  def destroy_mailer
    AdminUsersMailer.delay.user_destroyed_email(self)
  end

  def orphan_reports
    self.reports.each do |report|
      report.user = User.find_by_email(SYSTEM_USER_ACCOUNT_EMAIL)
      report.save
    end
  end

  def limited_servers
    if self.has_role?(:limited_servers) && (self.user_profile.server_groups.nil? || self.user_profile.server_groups.empty?)
      self.errors.add(:server_groups, 'invalid. If you select the limited servers role, you must specify at least one server group the user can have access to.')
    end
  end

  def setup_profile
    self.build_user_profile
    self.save
  end
end

app/controllers/api/reports_controller.rb
class API::ReportsController < ApplicationController
  load_and_authorize_resource
  before_filter :owner_check_read, only: [:generate, :generate_status]

  def generate
    report = Report.find(params[:id])
    timestamp = Time.now.in_time_zone(current_user.time_zone)
    reports_dir = Rails.root.join('public', 'generated_reports')
    Dir.mkdir reports_dir unless Dir.exists?(reports_dir)

    report_name = "#{timestamp.strftime('%m-%d-%Y_%H_%M_%S')}_#{report.name}.pdf"


    email_address = params[:email_address].empty? ? nil : params[:email_address]
    job = ReportGenerator.perform_async(params[:id], report_name, current_user.id, email_address)

    respond_to do |format|
      format.json do
        render json: {
            :status => 'queued',
            :job_id => job,
            :report_id => report.id,
            :report_pdf => "/generated_reports/#{report_name}.pdf"
        }.to_json
      end
    end
  end

  def generate_status
    report = Report.find(params[:id])
    job_id = params[:job_id]
    job_status = Sidekiq::Status::get_all (job_id)
    report_file = report.report_files.find {|s| s.job_id == job_id }
    report_pdf = report_file.nil? ? nil : "/generated_reports/#{report_file.file_file_name}"

    respond_to do |format|
      format.json do
        render json: {
            :status         => job_status['status'],
            :updated_time   => job_status['update_time'],
            :job_id         => job_id,
            :report_id      => report.id,
            :report_name    => report.name,
            :report_pdf     => report_pdf,
            :report_file_id => report_file.nil? ? nil : report_file.id
        }.to_json
      end
    end
  end

  def user_report_files
    report = Report.find(params[:id])

    @report_files = report.report_files.find_all {|f| f.user == current_user }
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource
  before_filter :owner_check_modify, only: [:edit, :update, :destroy]
  before_filter :owner_check_read, only: [:show, :generate]


  # GET /reports
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /reports/1
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        pdf_hash = @report.setup_pdf(params[:debug])

        render pdf: @report.name,
               show_as_html: params[:debug],
               :locals => {
                 :report    => @report,
                 :graphs    => pdf_hash[:graphs],
                 :app_info  => pdf_hash[:app_info]
               }
      end
    end
  end

  # GET /reports/new
  def new
    @report = Report.new
    @user = current_user
    @users = User.order(:email).all(:conditions => ['id != ?', @user.id]).select { |user| user.user_profile.allow_shared_reports? }
    setup_graph_types

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
    @user = current_user
    @users = User.order(:email).all(:conditions => ['id != ?', @user.id]).select { |user| user.user_profile.allow_shared_reports? }
    setup_graph_types
  end

  # POST /reports
  def create
    @report = Report.new(params[:report])
    @report.user = current_user
    @user = current_user
    @users = User.order(:email).all(:conditions => ['id != ?', @report.user.id]).select { |user| user.user_profile.allow_shared_reports? }

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /reports/1
  def update
    @report = Report.find(params[:id])
    @user = current_user
    @users = User.order(:email).all(:conditions => ['id != ?', @report.user.id]).select { |user| user.user_profile.allow_shared_reports? }

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /reports/1
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
    end
  end

  def generate
    @report = Report.find(params[:id])

    @email_address = params[:report_generation_information][:email]

    respond_to do |format|
      format.js
    end
  end


  private
  def setup_graph_types
    @report.graph_types ||= Array.new
  end

  def owner_check_modify
    report = Report.find(params[:id])
    unless report.can_modify?(current_user)
      params[:redirect_to] = reports_path
      raise CanCan::AccessDenied
    end
  end
end

app/helpers/api/reports_helper.rb
module Api::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  def modify_allowed?(report)
    current_user.reports.include?(report) || current_user.has_role?(:report_admin)
  end

  def report_groups(report)
    group_str = Array.new

    report.applications.each do |application|
      group_str << "Application - #{application.name}"
    end

    report.application_families.each do |application_family|
      group_str << "Application Family - #{application_family.name}"
    end

    report.server_groups.each do |server_group|
      group_str << link_to("Server Group - #{server_group.name}", server_group)
    end

    group_str
  end

  def graph_image_types

  end
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, t('general.error')) %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :report_title %><br />
    <%= f.text_field :report_title %>
  </div>
  <div class="field">
    <%= f.label :schedule_report_run %><br />
    <%= f.check_box :schedule_report_run %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.collection_select :time_zone, ActiveSupport::TimeZone.all, :name, :to_s, {:selected => (@report.time_zone ? @report.time_zone : current_user.time_zone) } %>
  </div>
  <div id="report_schedule">
    <div class="field">
      <%= f.label :send_time %><br />
      <%= f.time_select :send_time %>
    </div>
    <div class="field">
      <%= f.label :send_day %><br />
      <%= f.select :send_day, Report::DAYS %>
    </div>
  </div>
  <div class="field">
    <%= f.label :mailing_list %><br />
    <%= f.text_area :mailing_list, :value => (@report.mailing_list ? (@report.mailing_list.kind_of?(Array) ? @report.mailing_list.join("\r\n") : @report.mailing_list) : '') %>
  </div>
  <div class="field">
    <%= f.label :graph_command %><br />
    <%= f.collection_select :graph_command_id, GraphCommand.order(:name).all.collect, :id, :to_s, {:selected => (@report.graph_command ? @report.graph_command.id : nil) } %>
  </div>

  <% if APP_CONFIG['application_info'] && APP_CONFIG['application_info']['enabled'] %>
    <div class="field">
      <%= f.label :applications %>
      <%= f.collection_select :application_ids, Application.order(:name).all.collect, :id, :name, {}, {:multiple => true} %>
    </div>
    <div class="field">
      <%= f.label :application_families %>
      <%= f.collection_select :application_family_ids, ApplicationFamily.order(:name).all.collect, :id, :name, {}, {:multiple => true} %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :server_groups %>
    <% if @user.has_role? :limited_servers  %>
       <%= f.collection_select :server_group_ids, @user.user_profile.server_groups.collect, :id, :name, {}, {:multiple => true} %>
    <% else %>
        <%= f.collection_select :server_group_ids, ServerGroup.order(:name).all.collect, :id, :name, {}, {:multiple => true} %>
    <% end %>
  </div>
  <div class="field server_select">
    <%= f.label :servers %>
    <% if @user.has_role? :limited_servers  %>
        <%= f.collection_select :server_ids, @user.user_profile.all_authorized_servers.collect, :id, :name, {}, {:multiple => true} %>
    <% else %>
        <%= f.collection_select :server_ids, Server.order(:name).all.collect, :id, :name, {}, {:multiple => true} %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :graph_types %>
    <% GraphType.sorted.each do |graph_type| %>
      <%= graph_type.name %><%= check_box_tag 'report[graph_type_ids][]', graph_type.id, @report.graph_types.nil? ? false : @report.graph_types.include?(graph_type) %>
    <% end %>
  </div>
  <% if APP_CONFIG['application_info'] && APP_CONFIG['application_info']['embed_in_reports'] %>
  <div class="field">
    <%= f.label :include_application_information, t('reports.include_application_information') %><br />
    <%= f.check_box :include_application_information %>
  </div>
  <div class="field">
    <%= f.label :show_all_applications, t('reports.show_all_applications.label') %> <br />
    <%= f.check_box :show_all_applications %> (<%= t('reports.show_all_applications.description') %>)
  </div>
  <% end %>
  <div id="additionaloptions" style="padding-top: 25px">
  <h3><%= t('general.additional_options') %>
    <button type="button" class="btn btn-default btn-xs fa fa-angle-down" id="additionaloptions_toggle"></button>
  </h3>

    <div id="additionaloptions_items" hidden="hidden">
      <div class="field">
        <%= f.label :public, t('reports._public_report') %><br />
        <%= f.check_box :public %>
      </div>
      <div class="field">
        <%= f.label :users, t('shared_reports.shared_with') %>
        <%= f.collection_select :user_ids, @users.collect {|u| [ u.full_name_comma, u.id ] }, :last, :first, {}, {:multiple => true} %>
      </div>
      <div class="field">
        <%= f.label :graph_source, t('graph_sources.graph_source') %>
        <%= f.collection_select(:graph_source_id, GraphSource.all.collect {|u| [ u.name, u.id ] }, :last, :first, {:selected => (@report.graph_source.nil? ? default_graph_source: @report.graph_source.id)}) if GraphSource.count > 0 %>
      </div>
      <div class="field">
        <%= f.label :image_type, t('reports.graph_image_type') %>
        <%= f.collection_select(:image_type, Report::IMAGE_TYPES.select { |it| it != :default }, :last, :first, {:selected => (@report.get_image_type)}) %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<tr id="report_<%= report.id %>">
  <td><%= link_to report.name, report %></td>
  <td><%= bool_to_word(report.schedule_report_run).capitalize %></td>
  <td><%= report.schedule_report_run ? report.send_time.strftime('%I:%M:%S %p') : t('general.na') %></td>
  <td><%= (report.send_day.nil? || !report.schedule_report_run) ? t('general.na') : report.send_day.capitalize %></td>
  <td><%= report.user.nil? ? t('general.na') : user_public_link(report.user) %></td>
  <td>
    <% if modify_allowed? report %>
        <% if can? :edit, Report %>
            <%= link_to t('general.edit'), edit_report_path(report) %>
        <% end %>
        <% if can? :destroy, Report %>
            <%= link_to t('general.delete'), report, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    <% end %>
  </td>
</tr>

app/views/reports/edit.html.erb
<h1><%= t('general.editing') % t('reports.report') %></h1>

<%= render 'form' %>
<br />
<br />
<br />
<%= render 'layouts/view_footer' %>

app/views/reports/generate.js.erb
$.ajax({
    url: "<%= generate_api_report_path(@report.id, :email_address =>  @email_address) %>"
    })
    .done  (function(data, textStatus, jqXHR){
        if (data.status == "queued" || data.status == "working") {
            $.getJSON("<%= generate_status_api_report_path(@report.id) %>?job_id=" + data.job_id, addReport);
            displayNotice('Report <%= link_to @report.name, @report %> generation has been initiated.');
        }
    })
    .fail  (function(jqXHR, textStatus, errorThrown) {
        displayAlert("Generation of report file <a href='/report_files/" + report_file_id + "'>" + report_name + "<\/a> failed to be queued");
    })
    .always(function(jqXHROrData, textStatus, jqXHROrErrorThrown) {
    });


function addReport(data) {
    addPendingReport(data.job_id, data.report_file_id, "<%= @report.name %>", data.report_id);
}

app/views/reports/generate.pdf.erb
<head>
  <title>
    <%= report.report_title unless report.report_title.nil? && report.report_title.empty? %>
  </title>
  <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
  <%= wicked_pdf_javascript_include_tag "application" %>
</head>
<body>
    <div id="header">
    <% if !report.report_title.nil? && !report.report_title.empty? %>
        <h3 style="text-align: center"><%= report.report_title %></h3>
    <% end %>
    </div>
    <div id="content">
    <% report.servers_to_include.each do |server| %>
        <div style="page-break-after: always; width: 125%;">
        <h3><%= "#{server.name}" %></h3>
        <% added_graphs = Array.new %>
        <% graphs[server.name].each do |graph_path| %>
            <% next if added_graphs.include? graph_path %>
            <% next unless File.exist?(graph_path) %>
            <%= image_tag "#{graph_path}" %>

            <% added_graphs = graph_path %>
            <br />
            <br />
            <br />
        <% end %>
          <% if app_info && report.include_application_information? %>
              <div>
                <h3><%= t('reports.app_info.installed_applications') %></h3>
              <table border="1" id="<%= server.name %>_application_table" style="width: 125%;">
                <% next unless app_info[server.name] %>
                <thead>
                <tr>
                  <th><%= t('general.name') %></th>
                  <th><%= t('general.type') %></th>
                  <th><%= t('general.version') %></th>
                </tr>
                </thead>
                <tbody>
                <% app_info[server.name].each do |server_application| %>
                    <% next unless server_application['application']['name'] %>
                    <% next unless server_application['application']['major_application'] %>
                    <% unless report.show_all_applications?  %>
                      <% next if server_application['application_version']['application_version'].nil? || server_application['application_version']['application_version'].empty? %>
                    <% end %>
                    <tr>
                      <td><%= server_application['application']['name'] %></td>
                      <td><%= server_application['application']['app_type'] %></td>
                      <td><%= server_application['application_version']['application_version'] %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
              </div>
          <% end %>
        </div>
    <% end %>
    </div>
</body>

app/views/reports/show.html.erb
<h1><%= @report.name %>
  <% if can? :generate, @report %>
      <span class='actions'>
          <%= link_to t('reports.generate'), '#', id: 'generate_report_link' %>
      </span>
  <% end %>
</h1>

<div id="generate_report_form" hidden="true">
  <h3><%= t('reports.generate_report') %>:</h3>
  <%= form_for :report_generation_information, :url => generate_report_url, remote: true do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email, :autofocus => true %> (<%= t('reports.send_via_email_after') %>)
      </div>

      <div class="actions">
        <%= f.submit t('reports.generate'), :id=> 'action_button' %>
      </div>
  <% end %>
  <br />
  <br />
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= t('reports.report') %> <%= t('general.attributes') %>
    </div>
  <div class="panel-body">
    <table class="table">
      <thead>
      <tr>
        <th><%= t('reports.title') %></th>
        <th><%= t('shared_reports.shared_with') %></th>
        <th><%= t('graphs_commands.graph_command') %></th>
        <th><%= t('graphs.types') %></th>
        <th><%= t('reports.graph_image_type') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @report.report_title %></td>
        <td>
          <ul style="list-style: none outside none; padding: 2px;">
            <% @report.users.each do |user| %>
                <li><%= user_public_link user %></li>
            <% end %>
          </ul>
        </td>
        <td><%= @report.graph_command.name %></td>
        <td>
          <ul style="list-style: none outside none; padding: 2px;">
            <% GraphType.sort_by_display_order(@report.graph_types).each do |graph_type| %>
                <li><%= graph_type.name %></li>
            <% end %>
          </ul>
        </td>
        <td><%= @report.image_type ? @report.image_type.upcase : Report::IMAGE_TYPES[Report::IMAGE_TYPES[:default]][:name] %></td>
      </tbody>
    </table>
    <table class="table">
      <thead>
      <tr>
        <th><%= t('graph_sources.graph_source') %></th>
        <th><%= t('reports.groups') %></th>
        <th><%= t('reports.time_zone') %></th>
        <th><%= t('general.owner') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @report.graph_source ? @report.graph_source.name : t('general.na')%></td>
        <td>
          <ul style="list-style: none outside none; padding: 2px;">
            <% report_groups(@report).each do |report_group| %>
                <li><%= report_group.html_safe %></li>
            <% end %>
          </ul>
        </td>
        <td><%= @report.time_zone %></td>
        <td><%= user_public_link @report.user %></td>
      </tbody>
    </table>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('report_files.report_files') %> <%= render 'layouts/spinner', :spinner_id => 'report_generator_spinner', :spinner_title => t('reports.are_being_generated') %>
  </div>
  <div class="panel-body">
    <%= render 'report_files/report_files', :report_files => @report.report_files %>
  </div>
</div>

<h3><%= t('reports.additional_report_attributes') %>
  <button type="button" class="btn btn-default btn-xs fa fa-angle-down" id="additional_report_attributes_toggle"></button>
</h3>
<div id="additional_report_attributes" hidden="hidden">
<% if @report.schedule_report_run %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('reports.report') %> <%= t('reports.schedules') %>
    </div>
    <div class="panel-body">
    <table class='table'>
      <thead>
      <tr>
        <th><%= t('reports.scheduled_for_auto_run') %></th>
        <th><%= t('reports.send_time') %></th>
        <th><%= t('reports.send_day') %></th>
        <th><%= t('reports.mailing_list') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= bool_to_word(@report.schedule_report_run).capitalize %></td>
        <td><%= @report.send_time ? @report.send_time.strftime('%I:%M:%S %p') : t('general.na') %></td>
        <td><%= @report.send_day ? @report.send_day : t('general.na') %></td>
        <td>
          <ul style="list-style: none outside none; padding: 2px;">
            <% @report.mailing_list.each do |email| %>
                <li><%= email %></li>
            <% end %>
          </ul>
        </td>
      </tbody>
    </table>
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('server_groups.server_groups') %>
  </div>
  <div class="panel-body">
    <%= render 'server_groups/server_groups', :server_groups => @report.server_groups.order(:name) %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('servers.servers') %>
  </div>
  <div class="panel-body">
    <%= render 'servers/servers', :servers => @report.servers.order(:name) %>
  </div>
</div>
</div>

<br />
<br />
<% if @report.can_modify?(current_user) %>
    <%= edit_html(edit_report_path(@report), Report) %>
<% end %>
<%= link_to t('general.back'), reports_path %>